ComicBookStore/Models/Comics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ComicBookStore.Models
{
    public class Comics
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("SellerId")]
        public int? SellerId { get; set; }

        [DisplayName("Comics Title")]
        public string Name { get; set; }
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "US ${0:0.00}", ApplyFormatInEditMode = false)]
        public double Price { get; set; }

        [DisplayName("Genre")]
        public GenreEnum Genre { get; set; }
        public bool IsPhotoExists { get; set; }
        public virtual List<Review> Reviews { get; set; }
        [DisplayName("Seller")]
        public Seller Seller { get; set; }

        public Comics()
        {
        }

        public enum GenreEnum
        {
            [Display(Name = "Action")]
            ACTION,
            [Display(Name = "Horror")]
            HORROR,
            [Display(Name = "Drama")]
            DRAMA,
            [Display(Name = "Comedy")]
            COMEDY,
            [Display(Name = "History")]
            HISTORY
        }
    }
}

ComicBookStore/Controllers/ComicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComicBookStore.Models;
using System.IO;

namespace ComicBookStore.Controllers
{
    public class ComicsController : Controller
    {
        private ComicsContextDb db = new ComicsContextDb();

        // GET: Comics
        public ActionResult Index()
        {
            var comics = db.Comics.Include(g => g.Seller);
            return View(comics.ToList());
        }

        // GET: Comics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comics comics = db.Comics.Find(id);
            if (comics == null)
            {
                return HttpNotFound();
            }

            // Find the related seller
            comics.Seller = db.Sellers.Find(comics.SellerId);

            return View(comics);
        }

        // GET: Comics/Create
        public ActionResult Create()
        {
            ViewBag.SellerId = new SelectList(db.Sellers, "Id", "FirstName");
            return View();
        }

        // POST: Comics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SellerId,Name,Description,Price,Genre")] Comics comics, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                comics.IsPhotoExists = file != null && file.ContentLength > 0;
                db.Comics.Add(comics);
                db.SaveChanges();

                if (comics.IsPhotoExists)
                {
                    string fileName = comics.Id + ".png";
                    string newImage = Path.Combine(Server.MapPath("/Uploads"), fileName);
                    file.SaveAs(newImage);
                }

                return RedirectToAction("Index");
            }

            ViewBag.SellerId = new SelectList(db.Sellers, "Id", "FirstName", comics.SellerId);
            return View(comics);
        }

        // GET: Comics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comics comics = db.Comics.Find(id);
            if (comics == null)
            {
                return HttpNotFound();
            }
            ViewBag.SellerId = new SelectList(db.Sellers, "Id", "FirstName", comics.SellerId);
            return View(comics);
        }

        // POST: Comics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SellerId,Name,Description,Price,Genre,IsPhotoExists")] Comics comics, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = comics.Id + ".png";
                    string newImage = Path.Combine(Server.MapPath("/Uploads"), fileName);

                    // Saves the new photo
                    comics.IsPhotoExists = true;
                    file.SaveAs(newImage);
                }

                db.Entry(comics).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.SellerId = new SelectList(db.Sellers, "Id", "FirstName", comics.SellerId);
            return View(comics);
        }

        // GET: Comics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comics comics = db.Comics.Find(id);
            if (comics == null)
            {
                return HttpNotFound();
            }
            return View(comics);
        }

        // POST: Comics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comics comics = db.Comics.Find(id);

            if (comics.IsPhotoExists)
            {
                string fileName = comics.Id + ".png";
                string delImage = Path.Combine(Server.MapPath("/Uploads"), fileName);
                System.IO.File.Delete(delImage);
            }

            db.Comics.Remove(comics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Search(string comicsName, int? minPrice, int? maxPrice, string gener)
        {
            var comicsQuery = db.Comics.Include(x => x.Reviews);

            if (!string.IsNullOrEmpty(comicsName))
            {
                comicsQuery = comicsQuery.Where(x => x.Name.Contains(comicsName));
            }

            if (minPrice.HasValue)
            {
                if (minPrice >= 0)
                {
                    comicsQuery = comicsQuery.Where(x => x.Price >= minPrice);
                }
            }

            if (maxPrice.HasValue)
            {
                if (maxPrice >= 0)
                {
                    comicsQuery = comicsQuery.Where(x => x.Price <= maxPrice);
                }
            }

            if (!string.IsNullOrEmpty(gener))
            {
                comicsQuery = comicsQuery.Where(x => x.Genre.ToString().Contains(gener));
            }

            ViewBag.Comics = comicsQuery.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult AddReview(Review.Rank ComicsRank, string reviewTitle, string reviewAuthor, string reviewContent, string comicsId)
        {
            try
            {
                Review newReview = new Review
                {
                    ComicsRank = ComicsRank,
                    Title = reviewTitle,
                    Author = reviewAuthor,
                    Content = reviewContent,
                    ComicsID = int.Parse(comicsId),
                    PublicityDate = DateTime.Now
                };

                db.Reviews.Add(newReview);
                db.SaveChanges();

                return RedirectToAction("Search");
            }
            catch (Exception)
            {
                return RedirectToAction("Search");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ComicBookStore/Views/Comics/Create.cshtml
@model ComicBookStore.Models.Comics
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Comics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Comics</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SellerId, "Seller", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SellerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SellerId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="file">Upload Image:</label>
            <input type="file" name="file" id="file" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ComicBookStore/Views/Comics/Delete.cshtml
@model ComicBookStore.Models.Comics
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comics</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seller.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Seller.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPhotoExists)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPhotoExists)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComicBookStore/Views/Comics/Details.cshtml
@model ComicBookStore.Models.Comics
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Details</h2>
<div>
    <h4>Comics</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seller.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Seller.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPhotoExists)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPhotoExists)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ComicBookStore/Views/Comics/Edit.cshtml
@model ComicBookStore.Models.Comics
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Comics", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Comics</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.SellerId, "Seller", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SellerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SellerId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.IsPhotoExists)
        <div class="form-group">
            <label for="file">Upload Image:</label>
            <input type="file" name="file" id="file" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ComicBookStore/Views/Comics/Index.cshtml
@model IEnumerable<ComicBookStore.Models.Comics>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Seller.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Seller.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                <img src="/Uploads/@(item.Id + ".png")" height="40" width="70" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

ComicBookStore/Views/Comics/Search.cshtml
@model ComicBookStore.Models.Review
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="filter">
    <header>
        <h3>Filters</h3>
    </header>
    <div class="row">
        <div class="col-md-11">
            <section id="filter-comics">
                @using (Html.BeginForm("Search", "Comics", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="form-group">
                        <label class="col-md-6 control-label" for="comicsName">Comics name:</label>
                        <div class="col-md-6">
                            <input class="form-control" name="comicsName" id="comicsName" type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-6 control-label" for="minPrice">Minimum price:</label>
                        <div class="col-md-6">
                            <input class="form-control" name="minPrice" id="minPrice" type="number" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-6 control-label" for="maxPrice">Maximum price:</label>
                        <div class="col-md-6">
                            <input class="form-control" name="maxPrice" id="maxPrice" type="number" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-6 control-label" for="gener">Genre type:</label>
                        <div class="col-md-6">
                            <input class="form-control" name="gener" id="gener" type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-6 col-md-6">
                            <input class="btn btn-default" type="submit" value="filter" />
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</div>
<br />
<div class="comicses">
    @foreach (var comics in ViewBag.Comics)
    {
        <section id="comics-details">
            <table>
                <tr>
                    <td class="max-width">
                        <h2 class="header-color">
                            @comics.Name
                        </h2>
                        <article class="comics-article">
                            @comics.Description
                        </article>
                        <br />
                        <b>
                            Price:
                        </b>
                        USD $@comics.Price
                        <br />
                        <b>
                            Genre:
                        </b>
                        @comics.Genre
                    </td>
                    <td>
                        @if (comics.IsPhotoExists)
                        {
                            <img src="@("/Uploads/" + @comics.Id + ".png")" alt="No image" />
                        }
                        else
                        {
                            <canvas id="@comics.Name" class="noImage" width="200" height="100" style="border:1px solid #000000;">
                                No Image
                            </canvas>
                        }
                    </td>
                </tr>
            </table>
            <hr style="border-top: dotted 1px;" />
            <h3>
                @if (comics.Reviews.Count <= 0)
                {
                    @("No comments")
                }
                else
                {
                    @(comics.Reviews.Count + " comments:")
                }
            </h3>
            <section class="comments">
                <table>
                    @for (int l_iRevIndex = 0; l_iRevIndex < comics.Reviews.Count; l_iRevIndex++)
                    {
                        ComicBookStore.Models.Review currReview = comics.Reviews[l_iRevIndex];
                        <tr>
                            <th>
                                <div class="review-number">@(l_iRevIndex + 1)</div>
                                <h4 class="review-title header-color">@currReview.Title</h4>
                            </th>
                            <th>
                                @currReview.ComicsRank
                            </th>
                        </tr>

                            <tr>
                                <td>
                                    <i class="review-auth-details">@currReview.Author | <time datetime="@currReview.PublicityDate">@currReview.PublicityDate</time></i>
                                </td>
                            </tr>
                            <tr>
                                <td class="max-width">
                                    @currReview.Content
                                    <hr />
                                </td>
                            </tr>
                    }
                </table>
            </section>
            <div class="row">
                <div class="col-md-10">
                    @using (Html.BeginForm("AddReview", "Comics", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        <h3 class="add-comment-header header-color">Post a Comment</h3>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="ComicsRank">Comics rank:</label>
                                <div class="col-md-9">
                                    @Html.EnumDropDownListFor(model => model.ComicsRank, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="reviewTitle">Title:</label>
                                <div class="col-md-9">
                                    <input type="text" name="reviewTitle" id="reviewTitle" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="reviewAuthor">Author:</label>
                                <div class="col-md-9">
                                    <input type="text" name="reviewAuthor" id="reviewAuthor" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-2 control-label" for="reviewContent">Content:</label>
                                <div class="col-md-9">
                                    <textarea name="reviewContent" id="reviewContent" required></textarea>
                                </div>
                            </div>

                            <input type="hidden" id="comicsId" name="comicsId" value="@comics.Id" />

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input class="btn btn-default" type="submit" value="Post" />
                                </div>
                            </div>
                    }
                </div>
            </div>
        </section>
    }
</div>