ComicBookStore/Models/Seller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ComicBookStore.Models
{
    public class Seller
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Reliability { get; set; }

        public virtual List<Comics> Comicses { get; set; }

        public Seller()
        {
        }
    }
}

ComicBookStore/Controllers/SellersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using ComicBookStore.Models;

namespace ComicBookStore.Controllers
{
    [Authorize]
    public class SellersController : Controller
    {
        private ComicsContextDb db = new ComicsContextDb();

        // GET: Sellers
        public ActionResult Index()
        {
            return View(db.Sellers.ToList());
        }

        // GET: Sellers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Sellers.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        // GET: Sellers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sellers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,City,Street,Reliability")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                db.Sellers.Add(seller);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seller);
        }

        // GET: Sellers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Sellers.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        // POST: Sellers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,City,Street,Reliability")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seller).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seller);
        }

        // GET: Sellers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Sellers.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        // POST: Sellers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seller seller = db.Sellers.Find(id);
            db.Sellers.Remove(seller);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        public ActionResult Search(string firstName, string lastName, string city)
        {
            var sellersFiltered = db.Sellers.Include(x => x.Comicses);

            if (!string.IsNullOrEmpty(firstName))
            {
                sellersFiltered = sellersFiltered.Where(x => x.FirstName.Contains(firstName));
            }

            if (!string.IsNullOrEmpty(lastName))
            {
                sellersFiltered = sellersFiltered.Where(x => x.LastName.Contains(lastName));
            }

            if (!string.IsNullOrEmpty(city))
            {
                sellersFiltered = sellersFiltered.Where(x => x.City.Contains(city));
            }
            return View(sellersFiltered.ToList());
        }

        public string GroupByReliability()
        {
            var sellers = db.Sellers.GroupBy(seller => seller.Reliability,
                                            seller => seller.FirstName + " " + seller.LastName,
                                            (key, g) => new {
                                                Reliability = key,
                                                Sellers = g.ToList()
                                            }
                                        ).ToList();

            var resultSellers = new List<GroupByObject>();
            sellers.ForEach(d => resultSellers.Add(new GroupByObject(d.Reliability, Concat(d.Sellers))));

            return JsonConvert.SerializeObject(resultSellers);
        }

        private static string Concat(IEnumerable<string> source)
        {
            var sb = new StringBuilder();
            foreach (var s in source)
            {
                sb.Append(s + ", ");
            }
            if (sb.Length > 0)
            {
                var commaLength = ", ".Length;
                sb.Remove(sb.Length - commaLength, commaLength);
            }
            return sb.ToString();
        }

        [JsonObject(MemberSerialization.OptIn)]
        private class GroupByObject
        {
            [JsonProperty]
            private int Reliability { get; set; }
            [JsonProperty]
            private string Sellers { get; set; }

            public GroupByObject(int reliability, string sellers)
            {
                Reliability = reliability;
                Sellers = sellers;
            }
        }
    }

}

ComicBookStore/Views/Sellers/Create.cshtml
@model ComicBookStore.Models.Seller
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Seller</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Reliability, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reliability, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reliability, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ComicBookStore/Views/Sellers/Delete.cshtml
@model ComicBookStore.Models.Seller
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Seller</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reliability)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reliability)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ComicBookStore/Views/Sellers/Details.cshtml
@model ComicBookStore.Models.Seller
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Details</h2>
<div>
    <h4>Seller</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reliability)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reliability)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ComicBookStore/Views/Sellers/Edit.cshtml
@model ComicBookStore.Models.Seller
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Seller</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Reliability, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reliability, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reliability, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ComicBookStore/Views/Sellers/Index.cshtml
@model IEnumerable<ComicBookStore.Models.Seller>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reliability)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reliability)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

ComicBookStore/Views/Sellers/Search.cshtml
@model IEnumerable<ComicBookStore.Models.Seller>
<div class="sellers-filter">
    <header>
        <h3>Filters</h3>
    </header>
    <div class="row">
        <div class="col-md-11">
            <section id="filterBox">
                @using (Html.BeginForm("Search", "Sellers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="@Html.DisplayNameFor(model => model.FirstName)">@Html.DisplayNameFor(model => model.FirstName):</label>
                        <div class="col-md-6">
                            <input class="form-control" name="firstName" id="firstName" type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="@Html.DisplayNameFor(model => model.LastName)">@Html.DisplayNameFor(model => model.LastName):</label>
                        <div class="col-md-6">
                            <input class="form-control" name="lastName" id="lastName" type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="@Html.DisplayNameFor(model => model.City)">@Html.DisplayNameFor(model => model.City):</label>
                        <div class="col-md-6">
                            <input class="form-control" name="city" id="city" type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-6">
                            <input class="btn btn-default" type="submit" value="filter" />
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</div>

<div class="sellers-distribution">
    <header>
        <h4>Distribution Based On Seller's Reliability &nbsp;&nbsp;<input class="btn btn-default" type="button" value="Show" id="groupByBtn" onclick="showReliabilityGroupBy(this)" /></h4>
    </header>
    <section id="groupByReliabilitySection">
        <table id="sellersReliabilityTable">
            <thead>
                <tr>
                    <th>
                        <b>Reliability</b>
                    </th>
                    <th>
                        <b style="">Sellers</b>
                    </th>
                </tr>
            </thead>
            <tbody id="groupByListTBody"></tbody>
        </table>
    </section>
</div>
<article id="showSellers">
    <div class="filtered-sellers">
        @foreach (var seller in Model)
        {
            <section id="filteredListItem">
                <h3>@seller.FirstName @seller.LastName</h3>
                <p>
                    @for (int i = 0; i < seller.Reliability; i++)
                    {
                        @Html.Raw("&#9733;")
                    }
                    @for (int i = seller.Reliability; i < 10; i++)
                    {
                        @Html.Raw("&#9734;")
                    }

                    @(" (" + seller.Reliability + "/10)")
                </p>
                <p>@seller.Street, @seller.City </p>
                <hr />
                @foreach (var comics in seller.Comicses)
                {
                    @Html.Partial("_ComicsDetails", comics)
                    <br />
                }
            </section>
        }
    </div>
</article>
<script type="text/javascript">
    $(document).ready(function() {
        $('#groupByReliabilitySection').hide();
    });

    function showReliabilityGroupBy(inputBtn) {
        if ($(inputBtn).val() === 'Show') {
            $(inputBtn).val('Hide');

            $.getJSON('@Url.Action("GroupByReliability", "Sellers")')
                .success(function (listOfGroupedBySellers) {
                    for (var i = 0; i < listOfGroupedBySellers.length; i++) {
                        var groupedByItem = listOfGroupedBySellers[i];
                        $('#groupByListTBody').append("<tr><td>" + groupedByItem.Reliability + "</td><td>" + groupedByItem.Sellers + "</td></tr>");
                        console.log(groupedByItem);
                    }
                });
            $('#groupByReliabilitySection').show();
        } else {
            $('#groupByListTBody').empty();
            $(inputBtn).val('Show');
            $('#groupByReliabilitySection').hide();
        }
    }
</script>

ComicBookStore/Views/Sellers/_ComicsDetails.cshtml
@model ComicBookStore.Models.Comics
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Price)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Price)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Genre)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Genre)
    </dd>
</dl>