ComicBookStore/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using ComicBookStore.Models;
using WebGrease.Css.Extensions;

namespace ComicBookStore.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        public ActionResult Index()
        {
            return View("MapView");
        }

        public string GetAllSellersAddresses()
        {
            List<string> addresses = new List<string>();
            using (ComicsContextDb db = new ComicsContextDb())
            {
                db.Sellers.ForEach(seller => addresses.Add(ReformatSellerAddress(seller)));
            }

            return JsonConvert.SerializeObject(addresses);
        }

        private static string ReformatSellerAddress(Seller seller)
        {
            return seller.City + ", " + seller.Street;
        }

        public string GetAllSellersNames()
        {
            List<string> names = new List<string>();
            using (ComicsContextDb db = new ComicsContextDb())
            {
                db.Sellers.ForEach(seller => names.Add(ReformatSellerName(seller)));
            }

            return JsonConvert.SerializeObject(names);
        }

        private static string ReformatSellerName(Seller seller)
        {
            return seller.FirstName + " " + seller.LastName;
        }
    }
}

ComicBookStore/Controllers/ReviewsController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComicBookStore.Models;

namespace ComicBookStore.Controllers
{
    [Authorize]
    public class ReviewsController : Controller
    {
        private ComicsContextDb db = new ComicsContextDb();

        // GET: Reviews
        public ActionResult Index()
        {
            var reviews = db.Reviews.Include(r => r.Comics);
            return View(reviews.ToList());
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }

            // Find the related comics
            review.Comics = db.Comics.Find(review.ComicsID);

            return View(review);
        }

        // GET: Reviews/Create
        public ActionResult Create()
        {
            ViewBag.ComicsID = new SelectList(db.Comics, "Id", "Name");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ComicsID,ComicsRank,Title,Author,Content,PublicityDate")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ComicsID = new SelectList(db.Comics, "Id", "Name", review.ComicsID);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewBag.ComicsID = new SelectList(db.Comics, "Id", "Name", review.ComicsID);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ComicsID,ComicsRank,Title,Author,Content,PublicityDate")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ComicsID = new SelectList(db.Comics, "Id", "Name", review.ComicsID);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ComicBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ComicBookStore</title>
    <link rel="icon" href="@Url.Content("~/favicon.ico")" />

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" type="text/css" media="screen" />

    <link rel="stylesheet" href="~/Content/font-awesome-4.6.3/css/font-awesome.min.css" type="text/css" media="screen" />
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/css/main.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="~/Content/css/home.css" type="text/css" media="screen" />

    <script src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", false)
    }
</head>
<body>

    <div class="main">
        <div>
            <div class="navbar navbar-inverse navbar-fixed-top mainNavbar">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="#" class="pull-left">
                            <i id="storeLogo" class="fa fa-book" aria-hidden="true"></i>
                        </a>
                        @Html.ActionLink("ComicBookStore", "Home", "Home", new { area = "" }, new { @class = "navbar-brand storeLogoText" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav storeNav">
                            <li>@Html.ActionLink("Comics", "Search", "Comics")</li>
                            <li>@Html.ActionLink("Sellers", "Search", "Sellers")</li>
                            @if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Manage Comics", "Index", "Comics")</li>
                                <li>@Html.ActionLink("Manage Reviews", "Index", "Reviews")</li>
                                <li>@Html.ActionLink("Manage Sellers", "Index", "Sellers")</li>
                            }
                            <li>@Html.ActionLink("Contact", "Index", "Map")</li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
            <div class="container body-content">
                @RenderBody()
            </div>
            <footer>
                <h3>&copy; @DateTime.Now.Year - ComicBookStore</h3>
                <nav>
                    <a>@Html.ActionLink("Comics", "Search", "Guns")</a>
                    <a>@Html.ActionLink("Sellers", "Search", "Sellers")</a>
                    @if (Request.IsAuthenticated)
                    {
                        <a>@Html.ActionLink("Manage Comics", "Index", "Guns")</a>
                        <a>@Html.ActionLink("Manage Reviews", "Index", "Reviews")</a>
                        <a>@Html.ActionLink("Manage Sellers", "Index", "Sellers")</a>
                    }
                    <a>@Html.ActionLink("Contact", "Index", "Map")</a>
                </nav>
            </footer>
        </div>

</body>
</html>